### ISSUE TITLE
ability to exclude certain directories from the keyword search ?

### ISSUE THREAD

**Issue by shamaho** [gliviu/hyperclick-robot-framework#1]
Many thanks for this plugin - very useful for us robot framework users.

Is there any chance to include the ability to specify certain directories or Regex filepath to exclude from the files for keyword searching ?

If one uses robot framework say with Maven plugin, the keyword search will also include all the matches from source files under the "target" directory which is a nuisance. 

It's no point adding the results from the target sub-dir since it will be wiped-out with the next maven build having "clean"...

thanks in advance

**Comment by gliviu** [comment]
Yes it should be. Go into Atom settings, search for autocomplete-robot-framework package and there should be a configuration saying 'Names of directories or files to be excluded...'

Set for example 'target,deprecated' to exclude both directories from keyword searches.

Is that working for you?

**Comment by shamaho** [comment]
Doh! I totally missed that setting...
It works beautifully! Thanks
