### ISSUE TITLE
Multiple choices when prefix is specified

### ISSUE THREAD

**Issue by fardy316** [gliviu/hyperclick-robot-framework#2]
First off, thanks for this great plugin. Awesome job.

I got one project that contains the same keyword over different pages to verify that this page was properly loaded. I ran into an issue where, even if the resource file was specified into my keyword (Register.Verify Page Loaded), hyperclick showed me all the keywords found within my test cases.

![multipleresources](https://user-images.githubusercontent.com/26487683/52873549-47355180-311d-11e9-815f-c4959281aa4e.png)

Is there a possible way that hyperclick knows which keyword I'm refering to by using the resource's prefix ?

Thanks

**Comment by gliviu** [comment]
It should work if you have proper resources included.
Lets say you have two keyword files with identical content.
```
# Keywords1.robot, Keywords2.robot
*** Keywords ***
My first keyword
  Log  kw1
```

Then from your test case
```
*** Settings ***
Resource  Keywords1.robot

*** Test cases ***
Use case
  Keywords1.My first keyword
```

Without `Resource  Keywords1.robot`, hyperclick wouldn't know which keyword you are refering and would show all matches.
You can always check if resources are properly loaded by going to `Packages->Robot Framework->Show autocomplete status` from Atom menu.
It should show something like
```
File: test1.robot
    Status: Parsed/Ok
    Path: .../test1.robot
    Libraries
        BuiltIn
            Status: Loaded
            Source: .../BuiltIn.py
            Libdoc: /tmp/robot-lib-cache/BuiltIn.xml
    Resources
        Keywords1.robot
            Status: Resolved
            Path: .../Keywords1.robot
```

**Comment by fardy316** [comment]
I do have the proper Resource loaded in my script.

![resource](https://user-images.githubusercontent.com/26487683/52954179-7a632500-3357-11e9-9c8f-775f6e65a814.png)

And everything seems fine when I look at the Autocomplete Status from the menu. I do see the status and path for my _**Register.robot**_ resource.

```
    Resources
        Landing.robot
            Status: Resolved
            Path: C:\Users\********\Documents\RobotFramework-Projects\Dictionaries\dictionary-users\Resources\PO\Landing.robot
        TopNav.robot
            Status: Resolved
            Path: C:\Users\********\Documents\RobotFramework-Projects\Dictionaries\dictionary-users\Resources\PO\TopNav.robot
        Register.robot
            Status: Resolved
            Path: C:\Users\********\Documents\RobotFramework-Projects\Dictionaries\dictionary-users\Resources\PO\Register.robot
```

Thanks

**Comment by gliviu** [comment]
Before I publish could you give it a try?
```bash
# cd in some empty directory
git clone https://github.com/gliviu/hyperclick-robot-framework
cd hyperclick-robot-framework/
apm uninstall hyperclick-robot-framework
apm install
apm link
# restart Atom
```

**Comment by fardy316** [comment]
Just tried and it's working fine now. Thanks for the excellent work.

**Comment by gliviu** [comment]
Published https://github.com/gliviu/hyperclick-robot-framework/releases/tag/v1.9.0.
Don't forget to uninstall test version and install from atom store.
