### ISSUE TITLE
Not working with Atom version 1.37.0?

### ISSUE THREAD

**Issue by KenVercauteren** [gliviu/hyperclick-robot-framework#3]
Given:
Required packages are installed:
![image](https://user-images.githubusercontent.com/50573895/57764739-591a9680-7704-11e9-9de1-8c4766332255.png)
![image](https://user-images.githubusercontent.com/50573895/57765246-5c625200-7705-11e9-853c-2bce7a89b57e.png)

_When:_
Hovering over a keyword 
_Then:_
Expected result:
Keyword gets underlined and can be clicked to go to the definition
Actual result:
Keyword **doesn't** gets underlined and can be clicked to go to the definition

**Comment by gigi199596** [comment]
Hey,
On my side it's fine with ATOM 1.36.1 x64. My packages are in the same version as you.
Maybe reverting to 1.36.1 x64 could temporary fix it...

Cheers,
Gilles

**Comment by gliviu** [comment]
Tried with 1.37 and works fine. Maybe it is something else.
Can you open any .robot file and then go to 'Packages->Robot Framework-> Show autocomplete status'.
It should look like
```
File: test.robot
    Status: Parsed/Ok
    Path: ...\test.robot
    Libraries
        BuiltIn
            Status: Loaded
            Source: ...\python3\lib\site-packages\robot\libraries\BuiltIn.py
            Libdoc: ...\AppData\Local\Temp\robot-lib-cache\BuiltIn.xml
    Resources
        No resources imported
Environment:
    Python executable: ...\python.exe
    Python version: 3.7.0 
```

**Comment by KenVercauteren** [comment]
Thanks for the feedback.

Status:
`Multiple resources detected`

I only have one...

I tried using atom's dev tool but can't find any clue.

**Comment by gliviu** [comment]
That shouldn't be a problem. 'Go to definition' should work even when multiple sources are detected.
To exclude other causes I suggest you to create a simple robot file. Just name it 'test.robot' and try to see if your problem still persists.
```
* test cases *
tc1
  Log    xxx
```
When you hover `Log` you should be able to 'go to definition'.

**Comment by KenVercauteren** [comment]
Thanks for the feedback.

I followed your suggestion... I can click Log and than I get the definition of Log in buildin.py, so that's :-) working :-)

I can't get e.g. keywords from libraries which are imported in the resource file working?

**Comment by gliviu** [comment]
Maybe your resource file is outside Atom project folder. In order for resource lookup to work all .robot files must be visible from Atom.
For example lets assume you have a directory structure like
```
myrobotfiles
    dir1
        1.robot
    dir2
         2.robot
```
In Atom you only open dir2. In this case any resource reference to 1.robot will not work.
Otherwise this doesn't seem a problem with switching to atom 1.37. If you can build a minimal example on how to reproduce the issue that would be great. Resource imports work fine for me.

**Comment by KenVercauteren** [comment]
Thanks for your note!

.resource file is in the same directory as the .robot file I'm trying to get to work and that directory is an Atom project folder. Not sure what the root cause is so difficult to make an example
